export interface PasswordEntry {
    id: string;
    title: string;
    url: string;
    username: string;
    password: string;
    notes: string;
    createdAt: Date;
}

export const mockPasswords: PasswordEntry[] = [
    {
        id: '1',
        title: 'Facebook',
        url: 'https://www.facebook.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '2',
        title: 'Twitter',
        url: 'https://www.twitter.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '3',
        title: 'Instagram',
        url: 'https://www.instagram.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '4',
        title: 'LinkedIn',
        url: 'https://www.linkedin.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '5',
        title: 'GitHub',
        url: 'https://www.github.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '6',
        title: 'Google',
        url: 'https://www.google.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '7',
        title: 'Amazon',
        url: 'https://www.amazon.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '8',
        title: 'Netflix',
        url: 'https://www.netflix.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '9',
        title: 'Spotify',
        url: 'https://www.spotify.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '10',
        title: 'Dropbox',
        url: 'https://www.dropbox.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '11',
        title: 'Slack',
        url: 'https://www.slack.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '12',
        title: 'Trello',
        url: 'https://www.trello.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '13',
        title: 'Asana',
        url: 'https://www.asana.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '14',
        title: 'Zoom',
        url: 'https://www.zoom.us',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '15',
        title: 'Microsoft Teams',
        url: 'https://www.microsoft.com/teams',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '16',
        title: 'Skype',
        url: 'https://www.skype.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '17',
        title: 'WhatsApp',
        url: 'https://www.whatsapp.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '18',
        title: 'Telegram',
        url: 'https://www.telegram.org',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '19',
        title: 'Signal',
        url: 'https://www.signal.org',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
    {
        id: '20',
        title: 'Pinterest',
        url: 'https://www.pinterest.com',
        username: 'max.mustermann',
        password: '123456',
        notes: 'This is a note',
        createdAt: new Date(),
    },
];
