// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function CreateProfile(arg1:json.RawMessage):Promise<string>;

export function GetEnv(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function SelectDir():Promise<string>;

export function SetEnv(arg1:string,arg2:string):Promise<void>;
