// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToClipboard(arg1) {
  return window['go']['main']['App']['AddToClipboard'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function GenerateNewPassword() {
  return window['go']['main']['App']['GenerateNewPassword']();
}

export function GetEnv(arg1) {
  return window['go']['main']['App']['GetEnv'](arg1);
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetProfileFromPath(arg1) {
  return window['go']['main']['App']['GetProfileFromPath'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SelectDir() {
  return window['go']['main']['App']['SelectDir']();
}

export function UpdateMasterPassword(arg1) {
  return window['go']['main']['App']['UpdateMasterPassword'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function VerifyPassword(arg1, arg2) {
  return window['go']['main']['App']['VerifyPassword'](arg1, arg2);
}
