// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function GetEnv(arg1) {
  return window['go']['main']['App']['GetEnv'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetEnv(arg1, arg2) {
  return window['go']['main']['App']['SetEnv'](arg1, arg2);
}
