// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function CreateProfile(arg1:json.RawMessage):Promise<string>;

export function GetEnv(arg1:string):Promise<string>;

export function GetProfile():Promise<json.RawMessage>;

export function GetProfileFromPath(arg1:string):Promise<json.RawMessage>;

export function Quit():Promise<void>;

export function SelectDir():Promise<string>;

export function UpdateProfile(arg1:json.RawMessage):Promise<string>;

export function VerifyPassword(arg1:string,arg2:string):Promise<boolean>;
